WIP - Refactor MaterialFactory
NimbleSM/NimbleSM pull request #142
Opened 2021-02-03 23:28 UTC by uhetmaniuk

Closes #141 

These modifications will simplify the creation of one executable.

2021-02-10 22:10 UTC, japlews requested changes
I would prefer if you didn't push this. NimbleSMExtras utilizes the BlockMaterialInterfaceFactory and MaterialFactory to inject types and behaviors into NimbleSM. Maybe we can have a broader discussion about the future of NimbleSMExtras @uhetmaniuk @rjones-sandia?

2021-02-10 22:14 UTC, nmm0 commented
> I would prefer if you didn't push this. NimbleSMExtras utilizes the BlockMaterialInterfaceFactory and MaterialFactory to inject types and behaviors into NimbleSM. Maybe we can have a broader discussion about the future of NimbleSMExtras @uhetmaniuk @rjones-sandia?

Is there a way to keep NimbleSMExtras working with the refactor? Maybe this would be a good topic to discuss at the next meeting

2021-02-10 22:26 UTC, japlews commented
@nmm0 Yes, I think some changes might be required to this PR, but we could come to some consensus on the interface for Extras. It may be reasonable to set up some unit tests in NimbleSM which capture the interface use cases so that future changes don't break Nimble-as-a-library.

2021-02-11 02:00 UTC, uhetmaniuk commented
@nmm0 @japlews @rjones-sandia 

Talking about it sounds good.

I chose the approach of defining an abstract class `nimble::MaterialFactoryBase` in order to avoid any `Kokkos` dependency. The classes `nimble::MaterialFactory` and `nimble_kokkos::MaterialFactory` are derived from the base class. But we can change that approach.

Another class that saw similar changes is `nimble::ModelData`: an abstract base class is defined `nimble::BaseModelData` and two derived classes `nimble::ModelData` and `nimble_kokkos::ModelData`.  This class hierarchy could also be modified if it conflicts with other features.

2021-02-15 23:54 UTC, japlews commented on src/nimble_kokkos.h
> -void NimbleKokkosMain(std::shared_ptr<nimble_kokkos::MaterialFactory> material_factory,
nimble_kokkos::MaterialFactory, nimble_kokkos::ContactInterface, nimble_kokkos::BlockMaterialInterfaceFactory, and nimble::Parser are all classes which are overriden in Extras; so some interface to create these polymorphic objects outside of NimbleSM and pass them in is needed

2021-02-15 23:56 UTC, japlews commented on src/nimble_mpi.cc
> +  //
Same comment here: the type of the factory created needs to be prescribed through some kind of (preferably abstract) interface for compatibility with Extras.

2021-02-18 18:05 UTC, uhetmaniuk commented
Closing this pull request as it is superseded with other updates.

2021-02-18 18:05 UTC, closed without merging