Move CLI parsing
NimbleSM/NimbleSM pull request #202
Opened 2021-04-06 19:17 UTC by uhetmaniuk

Delete typedef `MaterialFactoryType`.

Closes #201

2021-04-06 20:28 UTC, uhetmaniuk commented
@japlews 
I have tried to address the concern that you raised when the Parser variable depends on the CLI flag.
I have also removed the typedef `MaterialFactoryType`.
I believe the local section in `int main()` should address the deletion of all Kokkos variables before the finalize.
Let me know if some tests are still failing.

2021-04-06 21:36 UTC, japlews requested changes
Minor fix needed to make this work.

2021-04-06 21:36 UTC, japlews commented on src/nimble.cc
> +  details::parseCommandLine(argc, argv, myFlags);
Can you make this accessible from the nimble_main.h header? Otherwise, all looks good!

2021-04-06 22:11 UTC, nmm0 reviewed
Thumbs up from me -- just contingent on the minor change @japlews requested. One thing we should definitely consider in the future is using a library for CLI parsing. There are definitely a lot of libraries that do it better than we do. That's pretty low priority though.

2021-04-07 13:38 UTC, japlews commented
Totally agree with @nmm0, it would be very easy to switch over to YAML and use a simple open source library for that.

2021-04-07 15:01 UTC, japlews approved these changes
Builds for me and tests pass.

2021-04-07 20:44 UTC, merged