#350: CI docker image testing
NimbleSM/NimbleSM pull request #351
Opened 2023-08-03 16:53 UTC by pierrepebay

Work in conjunction with https://github.com/NimbleSM/DockerTestImages/pull/2

2023-08-10 15:48 UTC, nmm0 requested changes
Excellent, just some minor comments

2023-08-10 15:48 UTC, nmm0 commented on ci/build.sh
> +fi
Maybe we can use the scope name given us to an environment variable here: https://github.com/NimbleSM/NimbleSM/blob/develop/.github/workflows/ubuntu20.04-gcc11-x64.yml#L34

Or construct the name of the environment in a similar manner

2023-08-10 16:00 UTC, pierrepebay commented on ci/build.sh
> +fi
That's a great idea, and to make things as clear as possible, I can change the spack environment names to the possible `SCOPE_NAME`s that way we don't even need this big if statement.

2023-08-10 22:19 UTC, pierrepebay commented on ci/build.sh
> +fi
https://github.com/NimbleSM/DockerTestImages/actions/runs/5826468563/job/15800501725#step:5:2213
`Error: 'pre_NimbleSMSerial+Trilinos': names must start with a letter, and only contain letters, numbers, _, and -` so this little trick can't happen 😔. I'll just use the `SCOPE_NAME` in the if statement.

2023-08-23 17:07 UTC, nmm0 commented on ci/ubuntu20.04-gcc11-x64.dockerfile
> +FROM pierrpebay/nimblesm:pr-2 AS build_nimble-stage
```suggestion
FROM nmm0/nimblesm-base-env:main AS build_nimble-stage
```

2023-08-23 18:56 UTC, nmm0 approved these changes
Looks good, thank you Pierre :)

2023-08-23 18:56 UTC, merged