#353: make kokkos required in contact
NimbleSM/NimbleSM pull request #355
Opened 2023-12-05 22:33 UTC by nmm0

Closes #353

2023-12-15 18:37 UTC, nmm0 commented
I managed to reproduce the sphere/plate contact error on my local system, but weirdly, it happend when I added ffast-math (pulled in from BVH). I'm not sure what exactly could be causing it here, since we aren't using distBVH in our ci builds, maybe the way in which spack is building something?

2024-01-16 22:08 UTC, nmm0 commented
I honestly can't get those CI issues to occur again.

2024-01-17 16:07 UTC, stmcgovern commented
The initial workflow ran over 30 days ago - so we can't just re-run it again. @nmm0 Do you want to make another commit to have the pipelines run some more to see if the issue re-occurs? Or is this sufficient?

2024-01-17 16:09 UTC, nmm0 commented
> The initial workflow ran over 30 days ago - so we can't just re-run it again. @nmm0 Do you want to make another commit to have the pipelines run some more to see if the issue re-occurs? Or is this sufficient?

@stmcgovern I ran it with a manual trigger here: https://github.com/NimbleSM/NimbleSM/actions/runs/7543914157 (doesn't show up on the PR)

2024-01-17 16:13 UTC, stmcgovern commented
I didn't see that. thanks @nmm0 ! I'll just re-run it again now and then I can review after pipelines finish.

2024-01-17 19:14 UTC, stmcgovern requested changes
I think this looks good. There are some remaining occurrences of the `use_kokkos` flag that I think should be cleaned up for clarity's sake.

2024-01-17 19:14 UTC, stmcgovern commented on src/nimble_cli.cc
The cli flag `--use_kokkos` should be removed.

2024-01-17 19:14 UTC, stmcgovern commented on src/nimble_cli.cc
def at line 58 and use at line 88 in nimble_cli.cc

2024-01-17 19:14 UTC, stmcgovern commented on src/nimble_parser.h
line 128

2024-01-17 19:14 UTC, stmcgovern commented on test/run_exodiff_test.py
I think the cli argument stuff should be removed here:
 ```
   if "use_kokkos" in cli_flag:
        log_file_name = base_name + ".kokkos.np" + str(num_ranks) + ".log"
 ```

2024-01-17 19:14 UTC, stmcgovern commented on test/run_exodiff_test.py
Related is the use of the flag in test/CMakeLists.txt and then in the command for the the tests that run (e.g. NimbleSM/test/contact/sphere_plate_contact/CMakeLists.txt at lines 14 and 26)

2024-01-18 18:29 UTC, stmcgovern approved these changes

2024-01-18 18:48 UTC, merged